[cloudreve]
# 你的 Cloudreve 实例 API 地址
url = https://cloudreve.example.com/api/v3
# 你的登录邮箱
username = username@example.com
# 你的登录密码
password = 114514

[upload]
# 要上传的本地文件的完整路径
# 本项仅供展示，大批量上传已被列入 todo，请文明催更
local = E:/Repository/Cloudreve-uploader/LICENSE
# 上传到 Cloudreve 的远程目录（/ 代表根目录）
remote = /test
# （可选）存储策略 ID，如不指定则使用默认策略
# 可通过浏览器开发者工具抓包获取
policy_id = MBu4